//! Shared protocol types between the app and shuai-agent.
//!
//! The agent appends one [`Envelope`] per line (JSONL) to `~/.shuai/events.jsonl`; the app
//! reads them through `shuai-agent watch`. Permission decisions flow back as
//! [`PermissionResponse`] files.

use serde::{Deserialize, Deserializer, Serialize, de::DeserializeOwned};
use serde_json::{Map, Value};

/// Wire protocol version shared by the app and shuai-agent.
pub const PROTOCOL_VERSION: u32 = 1;

/// Crate version.
pub fn version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

/// Which coding agent produced the event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Source {
    Claude,
    Codex,
}

/// tmux context of the hook process (from `$TMUX_PANE` / `$TMUX`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TmuxCtx {
    pub pane: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub socket: Option<String>,
}

/// One line of `events.jsonl`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Envelope {
    pub v: u32,
    pub seq: u64,
    pub ts_ms: u64,
    pub host: String,
    pub source: Source,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tmux: Option<TmuxCtx>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pid: Option<u32>,
    #[serde(deserialize_with = "lenient_event")]
    pub event: AgentEvent,
}

/// Fields common to every Claude Code hook payload.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct HookCtx {
    #[serde(default)]
    pub session_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transcript_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permission_mode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_type: Option<String>,
}

/// How a permission request ended.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PermissionOutcome {
    Allowed,
    Denied,
    /// Nobody answered in time; Claude falls back to its local dialog.
    Timeout,
    /// No app was watching, so the hook returned immediately.
    NotPresent,
}

/// A typed hook event. Unknown events are preserved as [`AgentEvent::Other`].
/// `raw` keeps the original hook payload for forward compatibility.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AgentEvent {
    SessionStart {
        #[serde(flatten)]
        ctx: HookCtx,
        #[serde(default)]
        source: Option<String>,
        #[serde(default)]
        model: Option<String>,
        #[serde(default)]
        session_title: Option<String>,
        #[serde(default)]
        raw: Value,
    },
    SessionEnd {
        #[serde(flatten)]
        ctx: HookCtx,
        #[serde(default)]
        reason: Option<String>,
        #[serde(default)]
        raw: Value,
    },
    UserPromptSubmit {
        #[serde(flatten)]
        ctx: HookCtx,
        #[serde(default)]
        prompt: Option<String>,
        #[serde(default)]
        raw: Value,
    },
    PreToolUse {
        #[serde(flatten)]
        ctx: HookCtx,
        #[serde(default)]
        tool_name: String,
        #[serde(default)]
        tool_input: Value,
        #[serde(default)]
        tool_use_id: Option<String>,
        #[serde(default)]
        raw: Value,
    },
    PostToolUse {
        #[serde(flatten)]
        ctx: HookCtx,
        #[serde(default)]
        tool_name: String,
        #[serde(default)]
        tool_input: Value,
        #[serde(default)]
        tool_use_id: Option<String>,
        #[serde(default)]
        raw: Value,
    },
    PermissionRequest {
        #[serde(flatten)]
        ctx: HookCtx,
        /// Generated by shuai-agent; empty until assigned.
        #[serde(default)]
        request_id: String,
        #[serde(default)]
        tool_name: String,
        #[serde(default)]
        tool_input: Value,
        #[serde(default)]
        tool_use_id: Option<String>,
        #[serde(default)]
        raw: Value,
    },
    PermissionDenied {
        #[serde(flatten)]
        ctx: HookCtx,
        #[serde(default)]
        tool_name: String,
        #[serde(default)]
        tool_input: Value,
        #[serde(default)]
        tool_use_id: Option<String>,
        #[serde(default)]
        raw: Value,
    },
    /// Written by the agent when a permission request is settled, so the app can clear its card.
    PermissionResolved {
        request_id: String,
        outcome: PermissionOutcome,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        session_id: Option<String>,
    },
    Notification {
        #[serde(flatten)]
        ctx: HookCtx,
        #[serde(default)]
        notification_type: Option<String>,
        #[serde(default)]
        message: Option<String>,
        #[serde(default)]
        raw: Value,
    },
    Stop {
        #[serde(flatten)]
        ctx: HookCtx,
        #[serde(default)]
        last_assistant_message: Option<String>,
        #[serde(default)]
        raw: Value,
    },
    SubagentStop {
        #[serde(flatten)]
        ctx: HookCtx,
        #[serde(default)]
        last_assistant_message: Option<String>,
        #[serde(default)]
        raw: Value,
    },
    StopFailure {
        #[serde(flatten)]
        ctx: HookCtx,
        #[serde(default)]
        error_type: Option<String>,
        #[serde(default)]
        error_message: Option<String>,
        #[serde(default)]
        raw: Value,
    },
    /// Codex `notify` hook: `agent-turn-complete`.
    AgentTurnComplete {
        #[serde(default)]
        thread_id: Option<String>,
        #[serde(default)]
        turn_id: Option<String>,
        #[serde(default)]
        cwd: Option<String>,
        #[serde(default)]
        input_messages: Vec<String>,
        #[serde(default)]
        last_assistant_message: Option<String>,
        #[serde(default)]
        raw: Value,
    },
    /// Anything we do not know (yet).
    Other {
        name: String,
        #[serde(default)]
        raw: Value,
    },
}

fn lenient_event<'de, D: Deserializer<'de>>(d: D) -> Result<AgentEvent, D::Error> {
    Ok(AgentEvent::from_value_lenient(Value::deserialize(d)?))
}

/// `PreToolUse` / `pre-tool-use` / `pre_tool_use` -> `pre_tool_use`.
fn normalize_name(name: &str) -> String {
    let mut out = String::new();
    let mut prev_lower = false;
    for c in name.chars() {
        if c == '-' || c == ' ' {
            out.push('_');
            prev_lower = false;
        } else if c.is_ascii_uppercase() {
            if prev_lower {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
            prev_lower = false;
        } else {
            out.push(c);
            prev_lower = c != '_';
        }
    }
    out
}

impl AgentEvent {
    /// Parse a tagged event object; anything that does not fit becomes [`AgentEvent::Other`].
    pub fn from_value_lenient(v: Value) -> AgentEvent {
        match serde_json::from_value::<AgentEvent>(v.clone()) {
            Ok(e) => e,
            Err(_) => {
                let name = v
                    .get("type")
                    .and_then(Value::as_str)
                    .unwrap_or("unknown")
                    .to_string();
                AgentEvent::Other { name, raw: v }
            }
        }
    }

    /// Build an event from a Claude Code hook name and its stdin JSON payload.
    pub fn from_hook(name: &str, payload: &Value) -> AgentEvent {
        let tag = normalize_name(name);
        let known = matches!(
            tag.as_str(),
            "session_start"
                | "session_end"
                | "user_prompt_submit"
                | "pre_tool_use"
                | "post_tool_use"
                | "permission_request"
                | "permission_denied"
                | "notification"
                | "stop"
                | "subagent_stop"
                | "stop_failure"
        );
        if known {
            let mut obj: Map<String, Value> = payload.as_object().cloned().unwrap_or_default();
            obj.insert("type".into(), Value::String(tag));
            obj.insert("raw".into(), payload.clone());
            if let Ok(e) = serde_json::from_value::<AgentEvent>(Value::Object(obj)) {
                return e;
            }
        }
        AgentEvent::Other {
            name: name.to_string(),
            raw: payload.clone(),
        }
    }

    /// Build an event from the single JSON argument Codex passes to its `notify` program.
    pub fn from_codex_notify(payload: &Value) -> AgentEvent {
        let s = |k: &str| payload.get(k).and_then(Value::as_str).map(str::to_string);
        if payload.get("type").and_then(Value::as_str) != Some("agent-turn-complete") {
            let name = s("type").unwrap_or_else(|| "unknown".into());
            return AgentEvent::Other {
                name,
                raw: payload.clone(),
            };
        }
        let input_messages = payload
            .get("input-messages")
            .and_then(Value::as_array)
            .map(|a| {
                a.iter()
                    .map(|m| {
                        m.as_str()
                            .map(str::to_string)
                            .unwrap_or_else(|| m.to_string())
                    })
                    .collect()
            })
            .unwrap_or_default();
        AgentEvent::AgentTurnComplete {
            thread_id: s("thread-id"),
            turn_id: s("turn-id"),
            cwd: s("cwd"),
            input_messages,
            last_assistant_message: s("last-assistant-message"),
            raw: payload.clone(),
        }
    }

    /// Wire tag of this event (`"pre_tool_use"`, ...).
    pub fn kind(&self) -> &'static str {
        match self {
            AgentEvent::SessionStart { .. } => "session_start",
            AgentEvent::SessionEnd { .. } => "session_end",
            AgentEvent::UserPromptSubmit { .. } => "user_prompt_submit",
            AgentEvent::PreToolUse { .. } => "pre_tool_use",
            AgentEvent::PostToolUse { .. } => "post_tool_use",
            AgentEvent::PermissionRequest { .. } => "permission_request",
            AgentEvent::PermissionDenied { .. } => "permission_denied",
            AgentEvent::PermissionResolved { .. } => "permission_resolved",
            AgentEvent::Notification { .. } => "notification",
            AgentEvent::Stop { .. } => "stop",
            AgentEvent::SubagentStop { .. } => "subagent_stop",
            AgentEvent::StopFailure { .. } => "stop_failure",
            AgentEvent::AgentTurnComplete { .. } => "agent_turn_complete",
            AgentEvent::Other { .. } => "other",
        }
    }

    /// Hook context, for events that carry one.
    pub fn ctx(&self) -> Option<&HookCtx> {
        match self {
            AgentEvent::SessionStart { ctx, .. }
            | AgentEvent::SessionEnd { ctx, .. }
            | AgentEvent::UserPromptSubmit { ctx, .. }
            | AgentEvent::PreToolUse { ctx, .. }
            | AgentEvent::PostToolUse { ctx, .. }
            | AgentEvent::PermissionRequest { ctx, .. }
            | AgentEvent::PermissionDenied { ctx, .. }
            | AgentEvent::Notification { ctx, .. }
            | AgentEvent::Stop { ctx, .. }
            | AgentEvent::SubagentStop { ctx, .. }
            | AgentEvent::StopFailure { ctx, .. } => Some(ctx),
            _ => None,
        }
    }

    pub fn session_id(&self) -> Option<&str> {
        self.ctx().map(|c| c.session_id.as_str())
    }
}

/// Decision of the app for a permission request.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Behavior {
    Allow,
    Deny,
}

/// Contents of `responses/<request_id>.json`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PermissionResponse {
    pub request_id: String,
    pub behavior: Behavior,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PermissionResponse {
    /// The JSON a `PermissionRequest` hook prints to stdout to decide.
    pub fn to_hook_output(&self) -> Value {
        let mut decision = Map::new();
        decision.insert(
            "behavior".into(),
            Value::String(
                match self.behavior {
                    Behavior::Allow => "allow",
                    Behavior::Deny => "deny",
                }
                .into(),
            ),
        );
        if let Some(m) = &self.message {
            decision.insert("message".into(), Value::String(m.clone()));
        }
        serde_json::json!({
            "hookSpecificOutput": {
                "hookEventName": "PermissionRequest",
                "decision": Value::Object(decision),
            }
        })
    }
}

/// Request ids become file names, so only `[A-Za-z0-9_-]{1,128}` is accepted.
pub fn is_valid_request_id(id: &str) -> bool {
    !id.is_empty()
        && id.len() <= 128
        && id
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
}

/// A line emitted by `shuai-agent watch`.
#[derive(Debug, Clone, PartialEq)]
pub enum WatchLine {
    Heartbeat,
    /// Sent once after the `--since` replay is drained: everything after it is live.
    CaughtUp,
    Event(Box<Envelope>),
}

impl WatchLine {
    pub fn decode(line: &str) -> Result<WatchLine, serde_json::Error> {
        let v: Value = serde_json::from_str(line)?;
        if v.get("type").and_then(Value::as_str) == Some("heartbeat") {
            return Ok(WatchLine::Heartbeat);
        }
        if v.get("type").and_then(Value::as_str) == Some("caught_up") {
            return Ok(WatchLine::CaughtUp);
        }
        Ok(WatchLine::Event(Box::new(serde_json::from_value(v)?)))
    }
}

/// Serialize as a single JSON line terminated by `\n`.
pub fn encode_line<T: Serialize>(v: &T) -> String {
    let mut s = serde_json::to_string(v).expect("serializable");
    s.push('\n');
    s
}

/// Decode complete JSONL lines of envelopes. Malformed complete lines are skipped; an
/// unterminated trailing line is left alone. Returns the envelopes and the number of bytes
/// consumed (everything up to and including the last `\n`).
pub fn decode_envelopes(input: &str) -> (Vec<Envelope>, usize) {
    decode_lines(input)
}

/// Generic version of [`decode_envelopes`].
pub fn decode_lines<T: DeserializeOwned>(input: &str) -> (Vec<T>, usize) {
    let end = input.rfind('\n').map_or(0, |i| i + 1);
    let items = input[..end]
        .lines()
        .filter(|l| !l.trim().is_empty())
        .filter_map(|l| serde_json::from_str(l).ok())
        .collect();
    (items, end)
}

/// Incremental splitter for a byte stream of JSONL: feed chunks, get complete lines.
#[derive(Debug, Default)]
pub struct LineDecoder {
    buf: Vec<u8>,
}

impl LineDecoder {
    pub fn push(&mut self, chunk: &[u8]) -> Vec<String> {
        self.buf.extend_from_slice(chunk);
        let mut out = Vec::new();
        while let Some(i) = self.buf.iter().position(|&b| b == b'\n') {
            let line: Vec<u8> = self.buf.drain(..=i).collect();
            let s = String::from_utf8_lossy(&line[..line.len() - 1]).into_owned();
            if !s.trim().is_empty() {
                out.push(s);
            }
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_matches_cargo_pkg() {
        assert_eq!(version(), env!("CARGO_PKG_VERSION"));
    }

    #[test]
    fn protocol_version_is_one() {
        assert_eq!(PROTOCOL_VERSION, 1);
    }
}
